alter table if exists public.folder_post drop constraint if exists FK4isox4m9attp7qql0l784crcj;
alter table if exists public.folder_post drop constraint if exists FK19jxmeff438m5pdsgxifixotn;
alter table if exists public.patron_folder drop constraint if exists FKeif0j9ptuxs6c25mfoygoj6kl;
alter table if exists public.patron_folder drop constraint if exists FK2jjqeo29ji105yp6ln5mio5ld;
alter table if exists public.post drop constraint if exists FKqbitxio9e3gwkkkhjhtntf16v;
alter table if exists public.post_patron drop constraint if exists FKm7q3ko7mgul95xqy1avkgnf96;
alter table if exists public.post_patron drop constraint if exists FKald2yoxpagema6ajgl6w4k03a;
alter table if exists public.post_tag drop constraint if exists FKac1wdchd2pnur3fl225obmlg0;
alter table if exists public.post_tag drop constraint if exists FKc2auetuvsec0k566l0eyvr9cs;
alter table if exists public.tag drop constraint if exists FKluryeqc4byhtnr4xhr47hjchw;
alter table if exists public.user_tags drop constraint if exists FK21732a8pkm7g7pt7xugpto6qg;
alter table if exists public.user_tags drop constraint if exists FKo2yjw3hl1xwujh0ysn3pfejk2;
drop table if exists public.folder cascade;
drop table if exists public.folder_post cascade;
drop table if exists public.image cascade;
drop table if exists public.patron cascade;
drop table if exists public.patron_folder cascade;
drop table if exists public.post cascade;
drop table if exists public.post_patron cascade;
drop table if exists public.post_tag cascade;
drop table if exists public.tag cascade;
drop table if exists public.user_tags cascade;
drop table if exists public.password_reset_token cascade;
create table public.folder (id bigserial not null, title varchar(40), description varchar(255), primary key (id));
create table public.folder_post (folder_id bigint not null, post_id bigint not null);
create table public.image (id bigserial not null, file varchar(255), primary key (id));
create table public.patron (id bigserial not null, email varchar(30) unique, username varchar(30) unique, password varchar(255), primary key (id));
create table public.patron_folder (folder_id bigint not null, patron_id bigint, primary key (folder_id));
create table public.post (id bigserial not null, image_id bigint unique, title varchar(40), description varchar(255), primary key (id));
create table public.post_patron (patron_id bigint, post_id bigint not null, primary key (post_id));
create table public.post_tag (post_id bigint not null, tag_id bigint not null);
create table public.tag (id bigserial not null, name varchar(30) unique, primary key (id));
create table public.user_tags (tag_id bigint not null, user_id bigint not null);
CREATE TABLE public.password_reset_token (id BIGSERIAL PRIMARY KEY, creation_date TIMESTAMP NOT NULL, is_used boolean not null default false, token VARCHAR(255) NOT NULL UNIQUE, user_id BIGINT NOT NULL, FOREIGN KEY (user_id) REFERENCES public.patron(id));
CREATE TABLE public.comment (id BIGSERIAL PRIMARY KEY, text VARCHAR(255), post_id BIGINT NOT NULL, author_username VARCHAR(255), date TIMESTAMP, CONSTRAINT fk_post FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE ON UPDATE CASCADE);
alter table if exists public.folder_post add constraint FK4isox4m9attp7qql0l784crcj foreign key (post_id) references public.post;
alter table if exists public.folder_post add constraint FK19jxmeff438m5pdsgxifixotn foreign key (folder_id) references public.folder;
alter table if exists public.patron_folder add constraint FKeif0j9ptuxs6c25mfoygoj6kl foreign key (patron_id) references public.patron;
alter table if exists public.patron_folder add constraint FK2jjqeo29ji105yp6ln5mio5ld foreign key (folder_id) references public.folder;
alter table if exists public.post add constraint FKqbitxio9e3gwkkkhjhtntf16v foreign key (image_id) references public.image;
alter table if exists public.post_patron add constraint FKm7q3ko7mgul95xqy1avkgnf96 foreign key (patron_id) references public.patron;
alter table if exists public.post_patron add constraint FKald2yoxpagema6ajgl6w4k03a foreign key (post_id) references public.post;
alter table if exists public.post_tag add constraint FKac1wdchd2pnur3fl225obmlg0 foreign key (tag_id) references public.tag;
alter table if exists public.post_tag add constraint FKc2auetuvsec0k566l0eyvr9cs foreign key (post_id) references public.post;
alter table if exists public.user_tags add constraint FK21732a8pkm7g7pt7xugpto6qg foreign key (tag_id) references public.tag;
alter table if exists public.user_tags add constraint FKo2yjw3hl1xwujh0ysn3pfejk2 foreign key (user_id) references public.patron;